
image: Ubuntu1804

install:
- git submodule update --init
- sudo apt update -qq
- sudo apt install python3-dev -y -qq
- sudo apt install cmake -y -qq
- mkdir temp
- cd temp
- wget https://github.com/Kitware/CMake/releases/download/v3.14.1/cmake-3.14.1-Linux-x86_64.sh
- sudo sh cmake-3.14.1-Linux-x86_64.sh --skip-license --prefix=/usr/local
- sudo apt install lsb-core -y -qq
- sudo apt install ocl-icd-opencl-dev -y -qq
- wget http://registrationcenter-download.intel.com/akdlm/irc_nas/vcp/15532/l_opencl_p_18.1.0.015.tgz
- tar -xvzf l_opencl_p_18.1.0.015.tgz
- cd l_opencl_p_18.1.0.015
- sudo ./install.sh -s $APPVEYOR_BUILD_FOLDER/ci/intelOpenCLSilent.cfg
- sudo ldconfig
- sudo apt install python3-pip -y
- pip3 install numpy

build: off

build_script:
- cd $APPVEYOR_BUILD_FOLDER
- mkdir build
- cd build
- cmake .. && make

test_script:
- ctest

